# Generated by Django 4.0.5 on 2024-06-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='private_key/'),
        ),
    ]
