# Generated by Django 4.0.5 on 2024-07-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
