# Generated by Django 4.0.5 on 2024-06-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
