# Generated by Django 4.0.5 on 2024-06-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0002_cert_is_signed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cert',
            name='student',
        ),
    ]
